#!/usr/bin/env bash
# bash implementation of shikinames
source $(dirname $0)/consts

request_tokens () {
	# link to shikinames shikimori's authorization page
	echo Tokens were not found, copy the link from authorization page:
	echo $AUTHORIZATION_PAGE
	echo and insert the authorization token
	read token

	# request for access and refresh tokens
	local result=$(curl -X POST "https://shikimori.one/oauth/token" \
		-H "User-Agent: shikinames" \
		-F grant_type="authorization_code" \
		-F client_id="atgTM364dtiQBh2uz5r5wbLaLjQesCKBCb3CvbHFPXA" \
		-F client_secret="WQu9MhHVx0OKs0yXe3BpT089M4QW3wwwRUGztq_q4JE" \
		-F code="${token}" \
		-F redirect_uri="urn:ietf:wg:oauth:2.0:oob")

	# parsing json for errors
	local err=$(echo "$result" | jq --raw-output ".error")
	if [[ $err != "null" ]] 
	then
		# returning error if something goes wrong
		echo $result
		exit 1 
	else
		# parsing json for tokens
		access=$(echo "$result" | jq --raw-output ".access_token")
		refresh=$(echo "$result" | jq --raw-output ".refresh_token")
		echo Tokens were acquired
	fi
} 

request_anime_json () {
	anime_json=$(curl -X GET "$URL$id" \
		-H "User-Agent: shikinames" \
		-H "Authorization: Bearer $access")
}

get_anime_json () {
	request_anime_json

	# parsing json for errors
	local err=$(echo "$anime_json" | jq --raw-output ".error")
	if [[ $err != "null" ]] 
	then
		# invalid token behavour
		echo $anime_json
		echo Your token is probaby invalid.
		echo Updating token...
		refresh_tokens
		request_anime_json
		local err=$(echo "$anime_json" | jq --raw-output ".error")
		if [[ $err = "null" ]] 
		then
			# something else more obscure happened
			echo $anime_json
		fi
	fi
}

get_names_from_json () {
	# name
	local name=$(echo $anime_json | jq --raw-output ".name")
	# english names
	local english=$(echo $anime_json | jq --raw-output ".english[]")
	# russian name
	local russian=$(echo $anime_json | jq --raw-output ".russian")
	# synonyms
	local synonyms=$(echo $anime_json | jq --raw-output ".synonyms[]")

	echo $synonyms
}

refresh_tokens () {
	local result=$(curl -X POST "https://shikimori.one/oauth/token" \
		-H "User-Agent: shikinames" \
		-F grant_type="refresh_token" \
		-F client_id="atgTM364dtiQBh2uz5r5wbLaLjQesCKBCb3CvbHFPXA" \
		-F client_secret="WQu9MhHVx0OKs0yXe3BpT089M4QW3wwwRUGztq_q4JE" \
		-F refresh_token="$refresh")

	local err=$(echo "$result" | jq --raw-output ".error")
	if [[ $err != "null" ]] 
	then
		# returning error if something goes wrong
		echo $result
		exit 1 
	else
		# parsing json for tokens
		access=$(echo "$result" | jq --raw-output ".access_token")
		refresh=$(echo "$result" | jq --raw-output ".refresh_token")
	fi
	write_tokens
}



get_tokens_from_cfg () {
	local cfg=$(cat ${CONFIG_PATH})
	access=$(echo $cfg | grep -Po "access=\K([a-zA-Z0-9-_]*[^;])")
	refresh=$(echo $cfg | grep -Po "refresh=\K([a-zA-Z0-9-_]*[^;])")
	# check if access is empty
	echo Tokens were successfully found
	#echo $access $refresh
	if [[ $access = "" ]]
	then
		# if it is, then that means there were never a request
		request_tokens
		write_tokens
	fi
}

write_tokens () {
	# simply writing to the file
	echo -e "access=${access};\nrefresh=${refresh};" > \
		${CONFIG_PATH}
	echo Tokens were written to $CONFIG_PATH
	#echo $(cat "$CONFIG_PATH")
}



get_id_from_link () {
	echo Input the link to the desired anime:
	read link 
	id=$(echo $link | grep -Po "/\K\d+")
	if [[ id = "" ]]
	then
		echo You entered wrong link
		exit 1
	fi
	echo Link parsing successful
	echo anime id is $id 
}

# main functionality
# creating config file (checking if it exists)
if [[ -f "${CONFIG_PATH}" ]]
then
	echo Config file already exists
else
	mkdir -p "${CONFIG_FOLDER}"
	touch "${CONFIG_PATH}"
	echo Config file created in ${CONFIG_PATH}
fi

#request_tokens
#write_tokens
get_tokens_from_cfg
get_id_from_link
get_anime_json
get_names_from_json

# todo:
# print the output function
# argv parser
# force-update tokens
# make a propper logging maybe?
